alias art='php artisan'
alias pa='php artisan'
alias tinker='php artisan tinker'
alias seed='php artisan db:seed'
alias fresh='php artisan migrate:fresh --seed'
alias serve='php artisan serve'
alias route='php artisan route:list'
alias clear='php artisan optimize:clear'
alias migrate='php artisan migrate'
alias rollback='php artisan migrate:rollback'
alias queue='php artisan queue:work'
alias horizon='php artisan horizon'

alias crun='composer run dev'
alias cbuild='composer run build'

alias cup='composer update'
alias ci='composer install'
alias co='composer outdated'
